version: '3'
services:
  redis:
    image: redis:latest
    hostname: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - visit-stats-network
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_MANAGEMENT_DISABLE: "false"
      RABBITMQ_DEFAULT_VHOST: "/"
    command: rabbitmq-server
  postgres:
    image: postgres
    container_name: postgres_container
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - visit-stats-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    networks:
      - visit-stats-network
    depends_on:
      - redis
      - rabbitmq
      - postgres
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: [ "npm", "run", "start:prod" ]
volumes:
  db-data:
  pgadmin-data:

networks:
  visit-stats-network:
    external: true